name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs:
  online-competition:

    runs-on: ubuntu-latest
    env: # Or as an environment variable
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.2-1' # any version from https://github.com/mamba-org/micromamba-releases
          environment-name: test-env
          init-shell: bash
          create-args: python=3.8
          cache-environment: true
      - run: pip install .[rl,test]
        shell: micromamba-shell {0}
      - run: pip install kaggle
        shell: micromamba-shell {0}
      - name: Install cffirmware
        run: |
          git clone -b drone_racing https://github.com/utiasDSL/pycffirmware.git
          cd pycffirmware
          git submodule update --init --recursive
          ./wrapper/build_linux.sh
        shell: micromamba-shell {0}
      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: micromamba-shell {0}
      - name: Export with kaggle
        run: kaggle competitions submit lsy-drone-racing-ws24 -f submission.csv -m "Automated submission"
        shell: micromamba-shell {0}

      