name: Testing  # Skips RL tests because stable-baselines3 comes with a lot of heavy-weight dependencies

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.2-1' # any version from https://github.com/mamba-org/micromamba-releases
          environment-name: test-env
          init-shell: bash
          create-args: python=3.8
          cache-environment: true
      - name: Install dependencies and package
        run: pip install .
        shell: micromamba-shell {0}
      - name: Install cffirmware
        run: |
          git clone -b drone_racing https://github.com/utiasDSL/pycffirmware.git
          cd pycffirmware
          git submodule update --init --recursive
          ./wrapper/build_linux.sh
        shell: micromamba-shell {0}
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests --cov=lsy_drone_racing 
        shell: micromamba-shell {0}
      